### PR TITLE
fix(hubble): encode/decode Chinese error after building package

### LINKED ISSUE #621: [Bug] Hubble 创建属性节点中文，数据库乱码
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: hugegraph/hubble:latest
- Backend: mysql
- OS: 4 CPUs,8 G RAM,CentOS 7.x 
- Data Size:  0

### Expected & Actual behavior (期望与实际表现)

创建节点中文变??

使用的镜像
image

image

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by FrostyHec**
## Purpose of the PR

- fix #621 #608 #302 https://github.com/apache/incubator-hugegraph/issues/1415 

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [x] Need tests and can be verified as follows:
    - I add the charset check at initEnv function( in launching), if charset configuration is wrong, it cannot pass the check so that the hubble will throw exception when launching.
    

## Does this PR potentially affect the following parts?

- [ ]  Nope
- [ ]  Dependencies (add/update license info) 
- [x]  Modify configurations
- [ ]  The public API
- [ ]  Other affects (typed here)

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [x]  `Doc - No Need`

### CODE REVIEW

**Review by imbajin — DISMISSED** [review]

File: hugegraph-hubble/hubble-dist/assembly/static/bin/start-hubble.sh [hunk 1]
```diff
@@ -42,7 +42,7 @@ for jar in "${LIB_PATH}"/*.jar; do
     class_path=${class_path}:${jar}
 done
 
-JAVA_OPTS="-Xms512m"
```
Comment (imbajin) [inline hugegraph-hubble/hubble-dist/assembly/static/bin/start-hubble.sh:45]: maybe add `export xxx` for system encoding env?

Also need test the docker version

Comment (imbajin) [reply hugegraph-hubble/hubble-dist/assembly/static/bin/start-hubble.sh:45]: image

**Review by imbajin — APPROVED** [review]

**Review by VGalaxies — APPROVED** [review]
