### PR TITLE
fix(loader): update shade plugin for spark loader

### LINKED ISSUE #562: [Improve] Update loader package shade plugin
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-hugegraph-toolchain/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Feature Description (功能描述)

- Cause: https://github.com/apache/incubator-hugegraph-toolchain/issues/464
- Solution: https://github.com/apache/incubator-hugegraph-toolchain/pull/480
- After introducing okhttp by https://github.com/apache/incubator-hugegraph-toolchain/pull/538, we need to recheck the packaging

img_v3_0265_930f7666-0731-4b83-b4c5-cda67a725deg

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liuxiaocs7**
## Purpose of the PR

- close #562   

## Verifying these changes

- [x] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [ ] Need tests and can be verified as follows:
    - xxx

## Does this PR potentially affect the following parts?

- [ ]  Nope
- [x]  Dependencies (add/update license info) 
- [ ]  Modify configurations
- [ ]  The public API
- [ ]  Other affects (typed here)

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [x]  `Doc - No Need`

### CODE REVIEW

**Comment by liuxiaocs7** [comment]
```bash
./bin/hugegraph-spark-loader.sh --master local[*] --name spark-hugegraph-loader --file ./example/spark/struct.json --host 192.168.110.214 --port 8080 --graph hugegraph
```

```
 Finished  load example/spark/vertex_software.json  data
24/01/06 18:21:19 INFO DAGScheduler: ResultStage 4 (foreachPartition at HugeGraphSparkLoader.java:155) finished in 0.696 s
24/01/06 18:21:19 INFO DAGScheduler: Job 4 is finished. Cancelling potential speculative or zombie tasks for this job
24/01/06 18:21:19 INFO TaskSchedulerImpl: Killing all running tasks in stage 4: Stage finished
24/01/06 18:21:19 INFO DAGScheduler: Job 4 finished: foreachPartition at HugeGraphSparkLoader.java:155, took 0.737901 s
24/01/06 18:21:19 INFO HugeGraphSparkLoader:
 Finished  load example/spark/edge_knows.json  data
24/01/06 18:21:19 INFO HugeGraphSparkLoader:
 ------------The data load task is complete-------------------

 insertSuccessCnt:       0
 ---------------------------------------------

24/01/06 18:21:19 INFO SparkUI: Stopped Spark web UI at http://root1-System-Product-Name.lan:4040
24/01/06 18:21:19 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
24/01/06 18:21:19 INFO MemoryStore: MemoryStore cleared
24/01/06 18:21:19 INFO BlockManager: BlockManager stopped
24/01/06 18:21:19 INFO BlockManagerMaster: BlockManagerMaster stopped
24/01/06 18:21:19 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
24/01/06 18:21:19 INFO SparkContext: Successfully stopped SparkContext
24/01/06 18:21:19 INFO SparkContext: SparkContext already stopped.
24/01/06 18:21:19 INFO SparkContext: SparkContext already stopped.
24/01/06 18:22:19 INFO ShutdownHookManager: Shutdown hook called
24/01/06 18:22:19 INFO ShutdownHookManager: Deleting directory /tmp/spark-d5bc3b10-ffc7-4b84-adaf-d2498a6893aa
24/01/06 18:22:19 INFO ShutdownHookManager: Deleting directory /tmp/spark-0b4951e1-070e-49e4-b5da-293b61ce7d15
```

File: hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh [hunk 1]
```diff
@@ -25,7 +25,7 @@ get_params "$@"
 echo "engine_params: $ENGINE_PARAMS"
 echo "hugegraph_params: $HUGEGRAPH_PARAMS"
 
-ASSEMBLY_JAR_NAME=$(find "${LIB_DIR}" -name 'apache-hugegraph-loader*.jar')
+ASSEMBLY_JAR_NAME=$(find "${LIB_DIR}" -name 'hugegraph-loader*.jar')
```
Comment (imbajin) [inline hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh:28]: why we change the prefix of jar file name

File: hugegraph-tools/pom.xml [hunk 2]
```diff
@@ -115,6 +115,10 @@
                     <groupId>log4j</groupId>
                     <artifactId>log4j</artifactId>
                 </exclusion>
+                <exclusion>
+                    <artifactId>guava</artifactId>
+                    <groupId>com.google.guava</groupId>
```
Comment (imbajin) [inline hugegraph-tools/pom.xml:120]: where do we use it? (in spark-connector?)

File: hugegraph-dist/scripts/dependency/known-dependencies.txt [hunk 3]
```diff
@@ -50,14 +50,14 @@ datanucleus-core-4.1.17.jar
...
-error_prone_annotations-2.18.0.jar
+error_prone_annotations-2.3.4.jar
 failureaccess-1.0.1.jar
 findbugs-annotations-1.3.9-1.jar
 flatbuffers-1.2.0-3f79e055.jar
 flatbuffers-java-1.9.0.jar
 groovy-all-2.4.21.jar
 gson-2.8.9.jar
-guava-32.0.1-jre.jar
+guava-30.0-jre.jar
```
Comment (imbajin) [inline hugegraph-dist/scripts/dependency/known-dependencies.txt:60]: could give more conflicts context (maybe paste pic in the comments)

**Review by imbajin — COMMENTED** [review]
currently in the  `release-1.2.0`, we can't load data well in spark-connector?

File: hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh (hunk 1 above)
Comment (liuxiaocs7) [reply hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh:28]: In `apache-hugegraph-toolchain-incubating-1.2.0/apache-hugegraph-loader-incubating-1.2.0/lib`

we only have:

```
hugegraph-loader-1.2.0.jar
```

without `apache` prefix

File: hugegraph-dist/scripts/dependency/known-dependencies.txt (hunk 3 above)
Comment (liuxiaocs7) [reply hugegraph-dist/scripts/dependency/known-dependencies.txt:60]: There is no guava conflict, but the version in hugegraph-common is 30.0-jre. The guava package does not seem to be used in the toolchain. Can it be inherited directly?

Comment (liuxiaocs7) [reply hugegraph-dist/scripts/dependency/known-dependencies.txt:60]: image

File: hugegraph-tools/pom.xml (hunk 2 above)
Comment (liuxiaocs7) [reply hugegraph-tools/pom.xml:120]: `com.google.j2objc:j2objc-annotations` conflict occurred after modifying the guava version to 30.0-jre

**Comment by liuxiaocs7** [comment]
> currently in the `release-1.2.0`, we can't load data well in spark-connector?

no, in `loader/HugeGraphSparkLoader`

File: hugegraph-dist/scripts/dependency/known-dependencies.txt (hunk 3 above)
Comment (imbajin) [reply hugegraph-dist/scripts/dependency/known-dependencies.txt:60]: > There is no guava conflict, but the version in hugegraph-common is 30.0-jre. The guava package does not seem to be used in the toolchain. Can it be inherited directly?

we do need to use common to manage `guava version` rather than define it separately (if common use 30.0, just  keep up with  it)

**Review by imbajin — APPROVED** [review]

**Comment by imbajin** [comment]
Note: we need basic test & more doc for the `spark-loader` & `spark-connector` (users may feel confused about them now)

**Review by javeme — APPROVED** [review]
