### PR TITLE
fix(client): update Content-Type in GraphsAPI for adding graphs

### LINKED ISSUE #713: [Bug] 在包 org.apache.hugegraph.api.graphs 中 create 方法定义了Content-Type 为 text/plain，会导致接口返回415错误。
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [x] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.7.0
- Toolchain Version: v1.7.0

### Expected & Actual behavior (期望与实际表现)

org.apache.hugegraph.api.graphs 包的源码：
Image
使用请求时调用接口时，响应415异常。
Image
实际上，如果使用application/json，是可以正常创建图的。
Image

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
nothing
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
nothing
```

### PR DESCRIPTION
**Pull request by chgjin**
fix #713 

Fix the error in the Content-Type definition in the create interface of Graphs, and change it to application/json.

### CODE REVIEW

File: hugegraph-client/src/main/java/org/apache/hugegraph/api/graphs/GraphsAPI.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ protected String type() {
     @SuppressWarnings("unchecked")
     public Map<String, String> create(String name, String cloneGraphName, String configText) {
         this.client.checkApiVersion("0.67", "dynamic graph add");
-        RestHeaders headers = new RestHeaders().add(RestHeaders.CONTENT_TYPE, "text/plain");
+        RestHeaders headers = new RestHeaders().add(RestHeaders.CONTENT_TYPE, "application/json");
```
Comment (imbajin) [inline hugegraph-client/src/main/java/org/apache/hugegraph/api/graphs/GraphsAPI.java]: Maybe we need to add a test for it to ensure it won't be broken in the future

**Review by imbajin — APPROVED** [review]
